### ISSUE TITLE
[DIAGRAM] Create Entity Relationship Diagram

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#1]
This ticket will track the design of the system's entity relationship diagram:

Tables to be included:
1. **user** 
- id INT 11 PK AUTO_INCREMENT NOT_NULL
- employee INT 11 FK NOT_NULL
- username VARCHAR 12 NOT_NULL
- password VARCHAR 255 NOT_NULL
- key VARCHAR 255 NOT_NULL
2. **employee**
- id INT 11 PK AUTO_INCREMENT NOT_NULL
- firstname VARCHAR 255 NOT_NULL
- middlename VARCHAR 255 NOT_NULL
- lastname VARCHAR 255 NOT_NULL
- dateofbirth DATE
- age INT 3 NOT_NULL
- position INT 11 NOT_NULL
- status ENUM "Active, Inactive" NOT_NULL
3. **position**
- id INT 11 PK AUTO_INCREMENT NOT_NULL
- description VARCHAR 120 NOT_NULL
4. **customer**
- id INT 11 PK AUTO_INCREMENT NOT_NULL
- firstname VARCHAR 255 NOT_NULL
- middlename VARCHAR 255 NOT_NULL
- lastname VARCHAR 255 NOT_NULL
- primarycontact VARCHAR 18 NOT NULL
- secondarycontact VARCHAR 18 NULL
- phonenumber VARCHAR 15 NULL
- phonenumberextension VARCHAR 10 NULL
- emailaddress VARCHAR 30 NULL
- addressnumber VARCHAR 255 NOT NULL

5. **brgy**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

6. **district**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

7. **city**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

8. **region**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

9. **patient**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

10. **patientdiagnosis**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

11. **diagnosis**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

12. **drugplan**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

13. **drug**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

14. **drugprescription**
- id INT 11 PK AUTO_INCREMENT NOT_NULL

**Comment by lhyra13** [comment]
in progress ...

![Screenshot 2024-03-28 092239](https://github.com/blackMisay/vet-management/assets/161996378/7d94bf57-5b88-4d7e-ba5b-a404a5cf4b2d)

**Comment by blackMisay** [comment]
This task did not reach completion before the deadline. I will move this ticket to the 2024.04.2 Sprint.
