### ISSUE TITLE
Pet module functionality

### ISSUE THREAD

**Issue by lhyra13** [blackMisay/vet-management#10]
Implement crud functionality for pet module.

**Comment by lhyra13** [comment]
Done with the update delete . error in adding pet but it appear on the database![IMG20240325011446.jpg](https://github.com/blackMisay/vet-management/assets/161996378/1f64bd52-5533-45a4-8dd5-3ccaea3443e3)

![IMG20240325011429.jpg](https://github.com/blackMisay/vet-management/assets/161996378/ddbb5ac8-d2a5-429e-a949-c5a8f3a55436)

. ![IMG20240325011446.jpg](https://github.com/blackMisay/vet-management/assets/161996378/53b60c31-b47d-42ba-93f7-c8b6b0c97e03)

**Comment by lhyra13** [comment]
![IMG20240325011504.jpg](https://github.com/blackMisay/vet-management/assets/161996378/069b2793-7a21-4b7b-b615-7c537555c3f5)

**Comment by lhyra13** [comment]
still in progress. dgvPatient didn't load when adding and updating data.
- done with inserting data in the combo box.

![Screenshot 2024-03-28 081830](https://github.com/blackMisay/vet-management/assets/161996378/a8b395dd-d515-4887-86bd-007ddfa02512)
![Screenshot 2024-03-28 081856](https://github.com/blackMisay/vet-management/assets/161996378/c4437f8e-a70b-4e55-92e2-52a763500d41)

**Comment by blackMisay** [comment]
This task did not reach completion before the deadline. I will move this ticket to the 2024.04.2 Sprint.
