### ISSUE TITLE
[DIAGRAM] Use Case Diagram

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#11]

**Comment by lhyra13** [comment]
use case diagram

![433938280_1082633199637389_5832463890016709805_n](https://github.com/blackMisay/vet-management/assets/161996378/288d877f-582c-40e8-ae91-28c58ef93cda)

**Comment by blackMisay** [comment]
Questions:

- What is the 'include' line between 'Generate Reports' and 'Process Payment' do?
- What does the yellow dotted circle represent in the diagram?
- What kind of reports do you intend to generate in the system?

**Comment by blackMisay** [comment]
This task did not reach completion before the deadline. I will move this ticket to the 2024.04.2 Sprint.
