### ISSUE TITLE
[DIAGRAM] Functional Decomposition Diagram

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#12]

**Comment by F3rnnn** [comment]
![received_333059396448325.jpeg](https://github.com/blackMisay/vet-management/assets/163960050/417349ef-462c-414a-afef-4e2c61325239)

**Comment by blackMisay** [comment]
@F3rnnn, please add the following:

- Veterinarian -> Add Veterinarian
- Treatment -> Add treatment plan
- Inventory
- Medical History -> View Pet Medical History
- Reports

Minor changes:
- Double check the spellings
- Diagram alignment

**Comment by F3rnnn** [comment]
![received_328903113528122.jpeg](https://github.com/blackMisay/vet-management/assets/163960050/d8720f88-0c47-4248-ab0c-b6a6d5b9fbff)

**Comment by blackMisay** [comment]
@F3rnnn, I'm good with the changes. Kindly upload this diagram to our folders. You may now closed this ticket. Thanks
