### ISSUE TITLE
Research Methodology for Agile and Scrum

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#14]

**Comment by blackMisay** [comment]
This task did not reach completion before the deadline. I will move this ticket to the 2024.04.2 Sprint.

**Comment by F3rnnn** [comment]
![received_450329584238162.png](https://github.com/blackMisay/vet-management/assets/163960050/429a07ff-7c17-495e-b060-057fef0fbcd7)

Product Backlog: The Product Owner creates a prioritized list of features, requirements, enhancements, and fixes, known as the Product Backlog. This list is dynamic and constantly updated to reflect changing customer needs and market conditions.

Sprint Backlog: At the beginning of each Sprint, the team selects a set of items from the Product Backlog to work on. This set of items becomes the Sprint Backlog, which the team will focus on during the current Sprint cycle.

Sprint Planning: Before each Sprint, the team meets to plan the work for the upcoming Sprint. This involves estimating the effort required to complete each item on the Sprint Backlog and defining the Sprint Goal, which is a specific, measurable, and attainable objective for the Sprint.

Sprint: The Sprint is the actual time period when the Scrum Team works together to finish an Increment. During the Sprint, the team holds daily stand-up meetings to review progress and address any challenges.

Daily Scrum: A short, daily meeting where team members check in and plan for the day. They report on work completed and voice any challenges in meeting Sprint Goals.

Sprint Review: At the end of the Sprint, the team gets together for an informal session to review the work completed and showcase it to stakeholders. The Product Owner might also rework the Product Backlog based on the current Sprint.

Sprint Retrospective: The team comes together to document and discuss what worked and what didn’t work during the Sprint. Ideas generated are used to improve future Sprints.
