### ISSUE TITLE
[DIAGRAM] Conceptual Framework

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#15]

**Comment by F3rnnn** [comment]
![received_3558385047746147.jpeg](https://github.com/blackMisay/vet-management/assets/163960050/7a756485-bc4e-4322-bb9a-a117f573a1b7)

**Comment by blackMisay** [comment]
@F3rnnn, kindly check all my review points

[REVIEW POINTS]
- Remove the VisualParadigm watermark
- Incorrect spellings (Requirements, Evaluation, etc.)
- Bullet alignment

**INPUT**
A. Knowledge Requirements
- System Architecture
- Database Design
- Programming Language
- Company's Information and Business Process
B. Software Requirements
- Visual Studio Community
- MariaDB database
- C#.NET
- MySqlConnector
C. Hardware Requirements
- Computer Unit
- Server
- Printer
- LAN Network

**PROCESS**
- What methodology are you using. Please indicate above the list.

**Comment by F3rnnn** [comment]
![IMG_20240330_002434.jpg](https://github.com/blackMisay/vet-management/assets/163960050/e2009b79-0726-4e40-bfb1-22cea8db7f66)

**Comment by F3rnnn** [comment]
![IMG_20240330_005706.jpg](https://github.com/blackMisay/vet-management/assets/163960050/f950e7b2-43f4-4ebc-b989-ef810096bf09)

**Comment by blackMisay** [comment]
I'm good with the Input.

@F3rnnn, have you studied the agile framework and its ceremonies? You may want to add additional ceremonies in the list like Sprint Retrospective, etc.

**Comment by F3rnnn** [comment]
![IMG_20240330_225733.jpg](https://github.com/blackMisay/vet-management/assets/163960050/c8c56ea0-195c-494e-b180-3f216728ce15)

**Comment by blackMisay** [comment]
Hi @F3rnnn save a copy of this diagram to our folder. I'm good with the design, nice job! You may now close this ticket, thanks.
