### ISSUE TITLE
[DCO_Diagram] Flow chart of Veterinary Clinic process

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#3]
Create a flow chart that shows Sahagun's full business process.

**Comment by lhyra13** [comment]
![received_7282510088496430.jpeg](https://github.com/blackMisay/vet-management/assets/161996378/e69d90f6-e2ff-4e90-baba-5339f243077e)

**Comment by lhyra13** [comment]
Updated Flowchart. ![received_430843926015372.jpeg](https://github.com/blackMisay/vet-management/assets/161996378/e90f85a9-3b06-4465-adbc-de8232ddd18d)
