### ISSUE TITLE
[DCO_Documentation] Update Chapter 3 2024.4

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#5]
This ticket will track the changes of Chapter 3 doco for April 2024

Requirements
- #3 
- #4

**Comment by blackMisay** [comment]
This task did not reach completion before the deadline. I will move this ticket to the 2024.04.2 Sprint.

**Comment by F3rnnn** [comment]
![chap3.docx](https://github.com/blackMisay/vet-management/files/14971209/chap3.docx)
