### ISSUE TITLE
[Service Module] Able to create negative amount in service price

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#73]
An issue was encountered during creating a new record in Service Module.

Branch: int/INT_2024_11
DB: vcms.sql (October 30)

The system able to create a service record with negative amount for service price.

Steps to recreate:
1. Add a new Service record.
2. Input a negative amount in the `Price` field.

See the image for additional reference:
![image](https://github.com/user-attachments/assets/c36130af-3c13-473d-8512-005fa9670a20)

Resolution change:
- Price currency should not be in dollar sign ($).
- Add a validation that don't allow negative amount in the service price.

**Comment by lhyra13** [comment]
confirm
