### ISSUE TITLE
[DCO_Documentation] Collate all used local and international foreign studies in Chapter 2

### ISSUE THREAD

**Issue by blackMisay** [blackMisay/vet-management#8]
Collate all used local and foreign literature used in Chapter 2. Create a folder in the GDrive for doco references.

**Comment by lhyra13** [comment]
Done uploaded to gDrive .

**Comment by lhyra13** [comment]
![Screenshot_2024-03-21-15-06-07-82_e2d5b3f32b79de1d45acd1fad96fbb0f.jpg](https://github.com/blackMisay/vet-management/assets/161996378/ca17c600-1ac6-4237-8c99-87fa9d9c80f1)
